[package]
name = "pistachio"
version = "0.1.0"
edition = "2021"


[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

# in Cargo.toml
[build-dependencies]
bootloader = "0.11.6"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
