[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
test = false

[profile.dev]
panic = "abort"


[profile.release]
panic = "abort"

[dependencies]
bit_field = "0.10.2"
bootloader_api = "0.11.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
